// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/localnetv1/services.proto

package localnetv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Set int32

const (
	Set_UnknownSet          Set = 0
	Set_ServicesSet         Set = 1
	Set_EndpointsSet        Set = 2
	Set_GlobalServiceInfos  Set = 10
	Set_GlobalEndpointInfos Set = 11
	Set_GlobalNodeInfos     Set = 12
)

var Set_name = map[int32]string{
	0:  "UnknownSet",
	1:  "ServicesSet",
	2:  "EndpointsSet",
	10: "GlobalServiceInfos",
	11: "GlobalEndpointInfos",
	12: "GlobalNodeInfos",
}

var Set_value = map[string]int32{
	"UnknownSet":          0,
	"ServicesSet":         1,
	"EndpointsSet":        2,
	"GlobalServiceInfos":  10,
	"GlobalEndpointInfos": 11,
	"GlobalNodeInfos":     12,
}

func (x Set) String() string {
	return proto.EnumName(Set_name, int32(x))
}

func (Set) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{0}
}

type Protocol int32

const (
	Protocol_UnknownProtocol Protocol = 0
	Protocol_TCP             Protocol = 1
	Protocol_UDP             Protocol = 2
	Protocol_SCTP            Protocol = 3
)

var Protocol_name = map[int32]string{
	0: "UnknownProtocol",
	1: "TCP",
	2: "UDP",
	3: "SCTP",
}

var Protocol_value = map[string]int32{
	"UnknownProtocol": 0,
	"TCP":             1,
	"UDP":             2,
	"SCTP":            3,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}

func (Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{1}
}

type WatchReq struct {
	// NodeName of the requester
	NodeName             string   `protobuf:"bytes,1,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchReq) Reset()         { *m = WatchReq{} }
func (m *WatchReq) String() string { return proto.CompactTextString(m) }
func (*WatchReq) ProtoMessage()    {}
func (*WatchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{0}
}

func (m *WatchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchReq.Unmarshal(m, b)
}
func (m *WatchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchReq.Marshal(b, m, deterministic)
}
func (m *WatchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchReq.Merge(m, src)
}
func (m *WatchReq) XXX_Size() int {
	return xxx_messageInfo_WatchReq.Size(m)
}
func (m *WatchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchReq.DiscardUnknown(m)
}

var xxx_messageInfo_WatchReq proto.InternalMessageInfo

func (m *WatchReq) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

type OpItem struct {
	// Types that are valid to be assigned to Op:
	//	*OpItem_Sync
	//	*OpItem_Reset_
	//	*OpItem_Set
	//	*OpItem_Delete
	Op                   isOpItem_Op `protobuf_oneof:"Op"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OpItem) Reset()         { *m = OpItem{} }
func (m *OpItem) String() string { return proto.CompactTextString(m) }
func (*OpItem) ProtoMessage()    {}
func (*OpItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{1}
}

func (m *OpItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpItem.Unmarshal(m, b)
}
func (m *OpItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpItem.Marshal(b, m, deterministic)
}
func (m *OpItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpItem.Merge(m, src)
}
func (m *OpItem) XXX_Size() int {
	return xxx_messageInfo_OpItem.Size(m)
}
func (m *OpItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OpItem.DiscardUnknown(m)
}

var xxx_messageInfo_OpItem proto.InternalMessageInfo

type isOpItem_Op interface {
	isOpItem_Op()
}

type OpItem_Sync struct {
	Sync *EmptyOp `protobuf:"bytes,1,opt,name=Sync,proto3,oneof"`
}

type OpItem_Reset_ struct {
	Reset_ *EmptyOp `protobuf:"bytes,4,opt,name=Reset,proto3,oneof"`
}

type OpItem_Set struct {
	Set *Value `protobuf:"bytes,2,opt,name=Set,proto3,oneof"`
}

type OpItem_Delete struct {
	Delete *Ref `protobuf:"bytes,3,opt,name=Delete,proto3,oneof"`
}

func (*OpItem_Sync) isOpItem_Op() {}

func (*OpItem_Reset_) isOpItem_Op() {}

func (*OpItem_Set) isOpItem_Op() {}

func (*OpItem_Delete) isOpItem_Op() {}

func (m *OpItem) GetOp() isOpItem_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *OpItem) GetSync() *EmptyOp {
	if x, ok := m.GetOp().(*OpItem_Sync); ok {
		return x.Sync
	}
	return nil
}

func (m *OpItem) GetReset_() *EmptyOp {
	if x, ok := m.GetOp().(*OpItem_Reset_); ok {
		return x.Reset_
	}
	return nil
}

func (m *OpItem) GetSet() *Value {
	if x, ok := m.GetOp().(*OpItem_Set); ok {
		return x.Set
	}
	return nil
}

func (m *OpItem) GetDelete() *Ref {
	if x, ok := m.GetOp().(*OpItem_Delete); ok {
		return x.Delete
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OpItem) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OpItem_Sync)(nil),
		(*OpItem_Reset_)(nil),
		(*OpItem_Set)(nil),
		(*OpItem_Delete)(nil),
	}
}

type EmptyOp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyOp) Reset()         { *m = EmptyOp{} }
func (m *EmptyOp) String() string { return proto.CompactTextString(m) }
func (*EmptyOp) ProtoMessage()    {}
func (*EmptyOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{2}
}

func (m *EmptyOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyOp.Unmarshal(m, b)
}
func (m *EmptyOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyOp.Marshal(b, m, deterministic)
}
func (m *EmptyOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyOp.Merge(m, src)
}
func (m *EmptyOp) XXX_Size() int {
	return xxx_messageInfo_EmptyOp.Size(m)
}
func (m *EmptyOp) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyOp.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyOp proto.InternalMessageInfo

type Ref struct {
	Set                  Set      `protobuf:"varint,1,opt,name=Set,proto3,enum=localnetv1.Set" json:"Set,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ref) Reset()         { *m = Ref{} }
func (m *Ref) String() string { return proto.CompactTextString(m) }
func (*Ref) ProtoMessage()    {}
func (*Ref) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{3}
}

func (m *Ref) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ref.Unmarshal(m, b)
}
func (m *Ref) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ref.Marshal(b, m, deterministic)
}
func (m *Ref) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ref.Merge(m, src)
}
func (m *Ref) XXX_Size() int {
	return xxx_messageInfo_Ref.Size(m)
}
func (m *Ref) XXX_DiscardUnknown() {
	xxx_messageInfo_Ref.DiscardUnknown(m)
}

var xxx_messageInfo_Ref proto.InternalMessageInfo

func (m *Ref) GetSet() Set {
	if m != nil {
		return m.Set
	}
	return Set_UnknownSet
}

func (m *Ref) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Value struct {
	Ref                  *Ref     `protobuf:"bytes,1,opt,name=Ref,proto3" json:"Ref,omitempty"`
	Bytes                []byte   `protobuf:"bytes,2,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{4}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetRef() *Ref {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (m *Value) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

type Service struct {
	Namespace   string            `protobuf:"bytes,1,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Type        string            `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Labels      map[string]string `protobuf:"bytes,8,rep,name=Labels,proto3" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Annotations map[string]string `protobuf:"bytes,9,rep,name=Annotations,proto3" json:"Annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IPs         *ServiceIPs       `protobuf:"bytes,4,opt,name=IPs,proto3" json:"IPs,omitempty"`
	IPFilters   []*IPFilter       `protobuf:"bytes,10,rep,name=IPFilters,proto3" json:"IPFilters,omitempty"`
	// true if the service maps the whole IP, not just individual ports.
	MapIP bool `protobuf:"varint,5,opt,name=MapIP,proto3" json:"MapIP,omitempty"`
	// Individual ports mapped for the this service
	Ports                  []*PortMapping `protobuf:"bytes,6,rep,name=Ports,proto3" json:"Ports,omitempty"`
	ExternalTrafficToLocal bool           `protobuf:"varint,7,opt,name=ExternalTrafficToLocal,proto3" json:"ExternalTrafficToLocal,omitempty"`
	// Types that are valid to be assigned to SessionAffinity:
	//	*Service_ClientIP
	SessionAffinity        isService_SessionAffinity `protobuf_oneof:"SessionAffinity"`
	InternalTrafficToLocal bool                      `protobuf:"varint,12,opt,name=InternalTrafficToLocal,proto3" json:"InternalTrafficToLocal,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                  `json:"-"`
	XXX_unrecognized       []byte                    `json:"-"`
	XXX_sizecache          int32                     `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{5}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Service) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Service) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *Service) GetIPs() *ServiceIPs {
	if m != nil {
		return m.IPs
	}
	return nil
}

func (m *Service) GetIPFilters() []*IPFilter {
	if m != nil {
		return m.IPFilters
	}
	return nil
}

func (m *Service) GetMapIP() bool {
	if m != nil {
		return m.MapIP
	}
	return false
}

func (m *Service) GetPorts() []*PortMapping {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *Service) GetExternalTrafficToLocal() bool {
	if m != nil {
		return m.ExternalTrafficToLocal
	}
	return false
}

type isService_SessionAffinity interface {
	isService_SessionAffinity()
}

type Service_ClientIP struct {
	ClientIP *ClientIPAffinity `protobuf:"bytes,11,opt,name=ClientIP,proto3,oneof"`
}

func (*Service_ClientIP) isService_SessionAffinity() {}

func (m *Service) GetSessionAffinity() isService_SessionAffinity {
	if m != nil {
		return m.SessionAffinity
	}
	return nil
}

func (m *Service) GetClientIP() *ClientIPAffinity {
	if x, ok := m.GetSessionAffinity().(*Service_ClientIP); ok {
		return x.ClientIP
	}
	return nil
}

func (m *Service) GetInternalTrafficToLocal() bool {
	if m != nil {
		return m.InternalTrafficToLocal
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Service) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Service_ClientIP)(nil),
	}
}

type IPFilter struct {
	// TargetIPs are the destination IPs to match (before DNAT)
	TargetIPs *IPSet `protobuf:"bytes,1,opt,name=TargetIPs,proto3" json:"TargetIPs,omitempty"`
	// SourceRanges are the CIDRs of IPs that are allowed by this filter rule
	SourceRanges         []string `protobuf:"bytes,2,rep,name=SourceRanges,proto3" json:"SourceRanges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPFilter) Reset()         { *m = IPFilter{} }
func (m *IPFilter) String() string { return proto.CompactTextString(m) }
func (*IPFilter) ProtoMessage()    {}
func (*IPFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{6}
}

func (m *IPFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPFilter.Unmarshal(m, b)
}
func (m *IPFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPFilter.Marshal(b, m, deterministic)
}
func (m *IPFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPFilter.Merge(m, src)
}
func (m *IPFilter) XXX_Size() int {
	return xxx_messageInfo_IPFilter.Size(m)
}
func (m *IPFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_IPFilter.DiscardUnknown(m)
}

var xxx_messageInfo_IPFilter proto.InternalMessageInfo

func (m *IPFilter) GetTargetIPs() *IPSet {
	if m != nil {
		return m.TargetIPs
	}
	return nil
}

func (m *IPFilter) GetSourceRanges() []string {
	if m != nil {
		return m.SourceRanges
	}
	return nil
}

type ServiceIPs struct {
	ClusterIPs           *IPSet   `protobuf:"bytes,1,opt,name=ClusterIPs,proto3" json:"ClusterIPs,omitempty"`
	ExternalIPs          *IPSet   `protobuf:"bytes,2,opt,name=ExternalIPs,proto3" json:"ExternalIPs,omitempty"`
	LoadBalancerIPs      *IPSet   `protobuf:"bytes,4,opt,name=LoadBalancerIPs,proto3" json:"LoadBalancerIPs,omitempty"`
	Headless             bool     `protobuf:"varint,3,opt,name=Headless,proto3" json:"Headless,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceIPs) Reset()         { *m = ServiceIPs{} }
func (m *ServiceIPs) String() string { return proto.CompactTextString(m) }
func (*ServiceIPs) ProtoMessage()    {}
func (*ServiceIPs) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{7}
}

func (m *ServiceIPs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceIPs.Unmarshal(m, b)
}
func (m *ServiceIPs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceIPs.Marshal(b, m, deterministic)
}
func (m *ServiceIPs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceIPs.Merge(m, src)
}
func (m *ServiceIPs) XXX_Size() int {
	return xxx_messageInfo_ServiceIPs.Size(m)
}
func (m *ServiceIPs) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceIPs.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceIPs proto.InternalMessageInfo

func (m *ServiceIPs) GetClusterIPs() *IPSet {
	if m != nil {
		return m.ClusterIPs
	}
	return nil
}

func (m *ServiceIPs) GetExternalIPs() *IPSet {
	if m != nil {
		return m.ExternalIPs
	}
	return nil
}

func (m *ServiceIPs) GetLoadBalancerIPs() *IPSet {
	if m != nil {
		return m.LoadBalancerIPs
	}
	return nil
}

func (m *ServiceIPs) GetHeadless() bool {
	if m != nil {
		return m.Headless
	}
	return false
}

type Endpoint struct {
	Hostname             string           `protobuf:"bytes,1,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	IPs                  *IPSet           `protobuf:"bytes,2,opt,name=IPs,proto3" json:"IPs,omitempty"`
	Local                bool             `protobuf:"varint,3,opt,name=Local,proto3" json:"Local,omitempty"`
	PortOverrides        map[string]int32 `protobuf:"bytes,4,rep,name=PortOverrides,proto3" json:"PortOverrides,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{8}
}

func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Endpoint) GetIPs() *IPSet {
	if m != nil {
		return m.IPs
	}
	return nil
}

func (m *Endpoint) GetLocal() bool {
	if m != nil {
		return m.Local
	}
	return false
}

func (m *Endpoint) GetPortOverrides() map[string]int32 {
	if m != nil {
		return m.PortOverrides
	}
	return nil
}

type IPSet struct {
	V4                   []string `protobuf:"bytes,1,rep,name=V4,proto3" json:"V4,omitempty"`
	V6                   []string `protobuf:"bytes,2,rep,name=V6,proto3" json:"V6,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPSet) Reset()         { *m = IPSet{} }
func (m *IPSet) String() string { return proto.CompactTextString(m) }
func (*IPSet) ProtoMessage()    {}
func (*IPSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{9}
}

func (m *IPSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPSet.Unmarshal(m, b)
}
func (m *IPSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPSet.Marshal(b, m, deterministic)
}
func (m *IPSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPSet.Merge(m, src)
}
func (m *IPSet) XXX_Size() int {
	return xxx_messageInfo_IPSet.Size(m)
}
func (m *IPSet) XXX_DiscardUnknown() {
	xxx_messageInfo_IPSet.DiscardUnknown(m)
}

var xxx_messageInfo_IPSet proto.InternalMessageInfo

func (m *IPSet) GetV4() []string {
	if m != nil {
		return m.V4
	}
	return nil
}

func (m *IPSet) GetV6() []string {
	if m != nil {
		return m.V6
	}
	return nil
}

type Port struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Protocol             Protocol `protobuf:"varint,2,opt,name=Protocol,proto3,enum=localnetv1.Protocol" json:"Protocol,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{10}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Port) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_UnknownProtocol
}

func (m *Port) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type PortMapping struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Protocol             Protocol `protobuf:"varint,2,opt,name=Protocol,proto3,enum=localnetv1.Protocol" json:"Protocol,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	NodePort             int32    `protobuf:"varint,4,opt,name=NodePort,proto3" json:"NodePort,omitempty"`
	TargetPort           int32    `protobuf:"varint,5,opt,name=TargetPort,proto3" json:"TargetPort,omitempty"`
	TargetPortName       string   `protobuf:"bytes,6,opt,name=TargetPortName,proto3" json:"TargetPortName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PortMapping) Reset()         { *m = PortMapping{} }
func (m *PortMapping) String() string { return proto.CompactTextString(m) }
func (*PortMapping) ProtoMessage()    {}
func (*PortMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{11}
}

func (m *PortMapping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortMapping.Unmarshal(m, b)
}
func (m *PortMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortMapping.Marshal(b, m, deterministic)
}
func (m *PortMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortMapping.Merge(m, src)
}
func (m *PortMapping) XXX_Size() int {
	return xxx_messageInfo_PortMapping.Size(m)
}
func (m *PortMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_PortMapping.DiscardUnknown(m)
}

var xxx_messageInfo_PortMapping proto.InternalMessageInfo

func (m *PortMapping) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PortMapping) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_UnknownProtocol
}

func (m *PortMapping) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *PortMapping) GetNodePort() int32 {
	if m != nil {
		return m.NodePort
	}
	return 0
}

func (m *PortMapping) GetTargetPort() int32 {
	if m != nil {
		return m.TargetPort
	}
	return 0
}

func (m *PortMapping) GetTargetPortName() string {
	if m != nil {
		return m.TargetPortName
	}
	return ""
}

type ClientIPAffinity struct {
	TimeoutSeconds       int32    `protobuf:"varint,1,opt,name=TimeoutSeconds,proto3" json:"TimeoutSeconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientIPAffinity) Reset()         { *m = ClientIPAffinity{} }
func (m *ClientIPAffinity) String() string { return proto.CompactTextString(m) }
func (*ClientIPAffinity) ProtoMessage()    {}
func (*ClientIPAffinity) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{12}
}

func (m *ClientIPAffinity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientIPAffinity.Unmarshal(m, b)
}
func (m *ClientIPAffinity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientIPAffinity.Marshal(b, m, deterministic)
}
func (m *ClientIPAffinity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientIPAffinity.Merge(m, src)
}
func (m *ClientIPAffinity) XXX_Size() int {
	return xxx_messageInfo_ClientIPAffinity.Size(m)
}
func (m *ClientIPAffinity) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientIPAffinity.DiscardUnknown(m)
}

var xxx_messageInfo_ClientIPAffinity proto.InternalMessageInfo

func (m *ClientIPAffinity) GetTimeoutSeconds() int32 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

type ServiceInfo struct {
	Hash                 uint64   `protobuf:"varint,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Service              *Service `protobuf:"bytes,2,opt,name=Service,proto3" json:"Service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{13}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetHash() uint64 {
	if m != nil {
		return m.Hash
	}
	return 0
}

func (m *ServiceInfo) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type EndpointInfo struct {
	Hash                 uint64              `protobuf:"varint,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Namespace            string              `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	SourceName           string              `protobuf:"bytes,3,opt,name=SourceName,proto3" json:"SourceName,omitempty"`
	ServiceName          string              `protobuf:"bytes,4,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	NodeName             string              `protobuf:"bytes,5,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	Endpoint             *Endpoint           `protobuf:"bytes,6,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	Conditions           *EndpointConditions `protobuf:"bytes,7,opt,name=Conditions,proto3" json:"Conditions,omitempty"`
	Topology             map[string]string   `protobuf:"bytes,8,rep,name=Topology,proto3" json:"Topology,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *EndpointInfo) Reset()         { *m = EndpointInfo{} }
func (m *EndpointInfo) String() string { return proto.CompactTextString(m) }
func (*EndpointInfo) ProtoMessage()    {}
func (*EndpointInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{14}
}

func (m *EndpointInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointInfo.Unmarshal(m, b)
}
func (m *EndpointInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointInfo.Marshal(b, m, deterministic)
}
func (m *EndpointInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointInfo.Merge(m, src)
}
func (m *EndpointInfo) XXX_Size() int {
	return xxx_messageInfo_EndpointInfo.Size(m)
}
func (m *EndpointInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointInfo proto.InternalMessageInfo

func (m *EndpointInfo) GetHash() uint64 {
	if m != nil {
		return m.Hash
	}
	return 0
}

func (m *EndpointInfo) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *EndpointInfo) GetSourceName() string {
	if m != nil {
		return m.SourceName
	}
	return ""
}

func (m *EndpointInfo) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *EndpointInfo) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *EndpointInfo) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

func (m *EndpointInfo) GetConditions() *EndpointConditions {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *EndpointInfo) GetTopology() map[string]string {
	if m != nil {
		return m.Topology
	}
	return nil
}

type EndpointConditions struct {
	Ready                bool     `protobuf:"varint,1,opt,name=Ready,proto3" json:"Ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndpointConditions) Reset()         { *m = EndpointConditions{} }
func (m *EndpointConditions) String() string { return proto.CompactTextString(m) }
func (*EndpointConditions) ProtoMessage()    {}
func (*EndpointConditions) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{15}
}

func (m *EndpointConditions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointConditions.Unmarshal(m, b)
}
func (m *EndpointConditions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointConditions.Marshal(b, m, deterministic)
}
func (m *EndpointConditions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointConditions.Merge(m, src)
}
func (m *EndpointConditions) XXX_Size() int {
	return xxx_messageInfo_EndpointConditions.Size(m)
}
func (m *EndpointConditions) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointConditions.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointConditions proto.InternalMessageInfo

func (m *EndpointConditions) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

type NodeInfo struct {
	Hash                 uint64   `protobuf:"varint,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Node                 *Node    `protobuf:"bytes,2,opt,name=Node,proto3" json:"Node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{16}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetHash() uint64 {
	if m != nil {
		return m.Hash
	}
	return 0
}

func (m *NodeInfo) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type Node struct {
	Name                 string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=Labels,proto3" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Annotations          map[string]string `protobuf:"bytes,3,rep,name=Annotations,proto3" json:"Annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{17}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Node) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

type GlobalWatchReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalWatchReq) Reset()         { *m = GlobalWatchReq{} }
func (m *GlobalWatchReq) String() string { return proto.CompactTextString(m) }
func (*GlobalWatchReq) ProtoMessage()    {}
func (*GlobalWatchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb45e71e3aadb99, []int{18}
}

func (m *GlobalWatchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalWatchReq.Unmarshal(m, b)
}
func (m *GlobalWatchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalWatchReq.Marshal(b, m, deterministic)
}
func (m *GlobalWatchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalWatchReq.Merge(m, src)
}
func (m *GlobalWatchReq) XXX_Size() int {
	return xxx_messageInfo_GlobalWatchReq.Size(m)
}
func (m *GlobalWatchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalWatchReq.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalWatchReq proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("localnetv1.Set", Set_name, Set_value)
	proto.RegisterEnum("localnetv1.Protocol", Protocol_name, Protocol_value)
	proto.RegisterType((*WatchReq)(nil), "localnetv1.WatchReq")
	proto.RegisterType((*OpItem)(nil), "localnetv1.OpItem")
	proto.RegisterType((*EmptyOp)(nil), "localnetv1.EmptyOp")
	proto.RegisterType((*Ref)(nil), "localnetv1.Ref")
	proto.RegisterType((*Value)(nil), "localnetv1.Value")
	proto.RegisterType((*Service)(nil), "localnetv1.Service")
	proto.RegisterMapType((map[string]string)(nil), "localnetv1.Service.AnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "localnetv1.Service.LabelsEntry")
	proto.RegisterType((*IPFilter)(nil), "localnetv1.IPFilter")
	proto.RegisterType((*ServiceIPs)(nil), "localnetv1.ServiceIPs")
	proto.RegisterType((*Endpoint)(nil), "localnetv1.Endpoint")
	proto.RegisterMapType((map[string]int32)(nil), "localnetv1.Endpoint.PortOverridesEntry")
	proto.RegisterType((*IPSet)(nil), "localnetv1.IPSet")
	proto.RegisterType((*Port)(nil), "localnetv1.Port")
	proto.RegisterType((*PortMapping)(nil), "localnetv1.PortMapping")
	proto.RegisterType((*ClientIPAffinity)(nil), "localnetv1.ClientIPAffinity")
	proto.RegisterType((*ServiceInfo)(nil), "localnetv1.ServiceInfo")
	proto.RegisterType((*EndpointInfo)(nil), "localnetv1.EndpointInfo")
	proto.RegisterMapType((map[string]string)(nil), "localnetv1.EndpointInfo.TopologyEntry")
	proto.RegisterType((*EndpointConditions)(nil), "localnetv1.EndpointConditions")
	proto.RegisterType((*NodeInfo)(nil), "localnetv1.NodeInfo")
	proto.RegisterType((*Node)(nil), "localnetv1.Node")
	proto.RegisterMapType((map[string]string)(nil), "localnetv1.Node.AnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "localnetv1.Node.LabelsEntry")
	proto.RegisterType((*GlobalWatchReq)(nil), "localnetv1.GlobalWatchReq")
}

func init() { proto.RegisterFile("api/localnetv1/services.proto", fileDescriptor_fcb45e71e3aadb99) }

var fileDescriptor_fcb45e71e3aadb99 = []byte{
	// 1250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xdd, 0x72, 0xd3, 0x46,
	0x14, 0x8e, 0x6c, 0xcb, 0xb1, 0x8f, 0x43, 0x22, 0x36, 0x0c, 0x78, 0x3c, 0x94, 0x06, 0x95, 0x42,
	0x48, 0x8b, 0x03, 0x81, 0x52, 0x4a, 0x3a, 0x0c, 0x38, 0x84, 0xc6, 0x33, 0x40, 0x34, 0x6b, 0x93,
	0xce, 0xf4, 0xa6, 0x15, 0xf6, 0xda, 0x68, 0xa2, 0xec, 0xaa, 0xda, 0x4d, 0x5a, 0xdf, 0xf4, 0x19,
	0xda, 0x07, 0xe9, 0x7d, 0xdf, 0xa1, 0xd3, 0x97, 0xe9, 0x13, 0x74, 0xf6, 0xac, 0x24, 0x4b, 0x8e,
	0x4d, 0x87, 0x8b, 0x4e, 0xef, 0x74, 0xce, 0xf9, 0xce, 0xcf, 0x9e, 0xbf, 0x5d, 0xc1, 0x47, 0x7e,
	0x14, 0x6c, 0x87, 0x62, 0xe0, 0x87, 0x9c, 0xa9, 0xb3, 0x7b, 0xdb, 0x92, 0xc5, 0x67, 0xc1, 0x80,
	0xc9, 0x76, 0x14, 0x0b, 0x25, 0x08, 0x4c, 0x45, 0xee, 0x4d, 0xa8, 0x7d, 0xeb, 0xab, 0xc1, 0x3b,
	0xca, 0x7e, 0x24, 0x2d, 0xa8, 0xbd, 0x16, 0x43, 0xf6, 0xda, 0x3f, 0x61, 0x4d, 0x6b, 0xc3, 0xda,
	0xac, 0xd3, 0x8c, 0x76, 0xff, 0xb0, 0xa0, 0x7a, 0x18, 0x75, 0x15, 0x3b, 0x21, 0xb7, 0xa1, 0xd2,
	0x9b, 0xf0, 0x01, 0x42, 0x1a, 0x3b, 0xeb, 0xed, 0xa9, 0xb5, 0xf6, 0xfe, 0x49, 0xa4, 0x26, 0x87,
	0xd1, 0xc1, 0x12, 0x45, 0x08, 0xf9, 0x0c, 0x6c, 0xca, 0x24, 0x53, 0xcd, 0xca, 0xfb, 0xb0, 0x06,
	0x43, 0x3e, 0x85, 0x72, 0x8f, 0xa9, 0x66, 0x09, 0xa1, 0x17, 0xf3, 0xd0, 0x23, 0x3f, 0x3c, 0x65,
	0x07, 0x4b, 0x54, 0xcb, 0xc9, 0x6d, 0xa8, 0x3e, 0x67, 0x21, 0x53, 0xac, 0x59, 0x46, 0xe4, 0x5a,
	0x1e, 0x49, 0xd9, 0xe8, 0x60, 0x89, 0x26, 0x80, 0x4e, 0x05, 0x4a, 0x87, 0x91, 0x5b, 0x87, 0xe5,
	0xc4, 0x97, 0xfb, 0x35, 0x94, 0x29, 0x1b, 0x91, 0xeb, 0xc6, 0x93, 0x3e, 0xc0, 0x6a, 0x51, 0xbf,
	0xc7, 0x94, 0xf1, 0x42, 0xa0, 0xe2, 0xf9, 0xea, 0x1d, 0x46, 0x53, 0xa7, 0xf8, 0xed, 0x3e, 0x05,
	0x1b, 0x23, 0xd1, 0xfa, 0x94, 0x8d, 0x92, 0x04, 0xcc, 0xfa, 0xa7, 0xe8, 0xe2, 0x12, 0xd8, 0x9d,
	0x89, 0x62, 0x12, 0x0d, 0xac, 0x50, 0x43, 0xb8, 0xbf, 0xdb, 0xb0, 0xdc, 0x33, 0xc5, 0x20, 0x57,
	0xa1, 0xae, 0x33, 0x2b, 0x23, 0x7f, 0x90, 0xa6, 0x7b, 0xca, 0xd0, 0xfe, 0xb1, 0x0e, 0x89, 0x7f,
	0xfd, 0xad, 0x79, 0xfd, 0x49, 0x64, 0xce, 0x5d, 0xa7, 0xf8, 0x4d, 0xbe, 0x84, 0xea, 0x4b, 0xff,
	0x2d, 0x0b, 0x65, 0xb3, 0xb6, 0x51, 0xde, 0x6c, 0xec, 0x7c, 0x5c, 0x3c, 0x0d, 0xba, 0x6a, 0x1b,
	0xc4, 0x3e, 0x57, 0xf1, 0x84, 0x26, 0x70, 0xf2, 0x02, 0x1a, 0xcf, 0x38, 0x17, 0xca, 0x57, 0x81,
	0xe0, 0xb2, 0x59, 0x47, 0xed, 0x1b, 0xf3, 0xb4, 0x73, 0x30, 0x63, 0x22, 0xaf, 0x48, 0x36, 0xa1,
	0xdc, 0xf5, 0x64, 0x52, 0xe0, 0xcb, 0x73, 0xf4, 0xbb, 0x9e, 0xa4, 0x1a, 0x42, 0x76, 0xa0, 0xde,
	0xf5, 0x5e, 0x04, 0xa1, 0x62, 0xb1, 0x6c, 0x02, 0xfa, 0xbb, 0x94, 0xc7, 0xa7, 0x42, 0x3a, 0x85,
	0xe9, 0x34, 0xbe, 0xf2, 0xa3, 0xae, 0xd7, 0xb4, 0x37, 0xac, 0xcd, 0x1a, 0x35, 0x04, 0xb9, 0x03,
	0xb6, 0x27, 0x62, 0x25, 0x9b, 0x55, 0xb4, 0x72, 0x25, 0x6f, 0x45, 0x0b, 0x5e, 0xf9, 0x51, 0x14,
	0xf0, 0x31, 0x35, 0x28, 0xf2, 0x10, 0x2e, 0xef, 0xff, 0xac, 0x58, 0xcc, 0xfd, 0xb0, 0x1f, 0xfb,
	0xa3, 0x51, 0x30, 0xe8, 0x8b, 0x97, 0x5a, 0xa3, 0xb9, 0x8c, 0x56, 0x17, 0x48, 0xc9, 0x63, 0xa8,
	0xed, 0x85, 0x01, 0xe3, 0xaa, 0xeb, 0x35, 0x1b, 0x78, 0xbe, 0xab, 0x79, 0x4f, 0xa9, 0xec, 0xd9,
	0x68, 0x14, 0xf0, 0x40, 0x4d, 0x0e, 0x96, 0x68, 0x86, 0xd7, 0x3e, 0xbb, 0x7c, 0xae, 0xcf, 0x15,
	0xe3, 0x73, 0xbe, 0xb4, 0xf5, 0x15, 0x34, 0x72, 0xd5, 0x22, 0x0e, 0x94, 0x8f, 0xd9, 0x24, 0x69,
	0x0f, 0xfd, 0xa9, 0x33, 0x72, 0xa6, 0x9b, 0x30, 0xe9, 0x0c, 0x43, 0x3c, 0x2e, 0x3d, 0xb2, 0x5a,
	0x4f, 0xc0, 0x99, 0x2d, 0xd5, 0x87, 0xe8, 0x77, 0x2e, 0xc2, 0x5a, 0x8f, 0x49, 0x19, 0x08, 0x9e,
	0x9e, 0xc8, 0xfd, 0x1e, 0x6a, 0x69, 0x2d, 0xc8, 0x36, 0xd4, 0xfb, 0x7e, 0x3c, 0x66, 0x4a, 0x97,
	0xdb, 0x3a, 0x3f, 0xa4, 0x5d, 0x4f, 0x0f, 0xcf, 0x14, 0x43, 0x5c, 0x58, 0xe9, 0x89, 0xd3, 0x78,
	0xc0, 0xa8, 0xcf, 0xc7, 0x38, 0x09, 0xe5, 0xcd, 0x3a, 0x2d, 0xf0, 0xdc, 0xbf, 0x2c, 0x80, 0x69,
	0x9f, 0x90, 0x7b, 0x00, 0x7b, 0xe1, 0xa9, 0x54, 0x2c, 0x7e, 0xaf, 0x93, 0x1c, 0x88, 0xdc, 0x87,
	0x46, 0x5a, 0x3e, 0xad, 0x53, 0x5a, 0xa4, 0x93, 0x47, 0x91, 0x5d, 0x58, 0x7b, 0x29, 0xfc, 0x61,
	0xc7, 0x0f, 0x7d, 0x3e, 0x30, 0xce, 0x2a, 0x8b, 0x14, 0x67, 0x91, 0x7a, 0x4d, 0x1e, 0x30, 0x7f,
	0x18, 0x32, 0x29, 0x71, 0x14, 0x6b, 0x34, 0xa3, 0xdd, 0xbf, 0x2d, 0xa8, 0xed, 0xf3, 0x61, 0x24,
	0x02, 0xae, 0x10, 0x28, 0xa4, 0xe2, 0xb9, 0x7d, 0x9a, 0xd2, 0xe4, 0x13, 0x33, 0x36, 0x0b, 0xc3,
	0xc5, 0x89, 0xb9, 0x04, 0xb6, 0xe9, 0x19, 0xe3, 0xc6, 0x10, 0xe4, 0x15, 0x5c, 0xd0, 0x7d, 0x7d,
	0x78, 0xc6, 0xe2, 0x38, 0x18, 0x32, 0x1d, 0xba, 0x9e, 0x82, 0x5b, 0x85, 0xe5, 0x9a, 0xc4, 0xd0,
	0x2e, 0x20, 0xcd, 0xf8, 0x16, 0xb5, 0x5b, 0x4f, 0x81, 0x9c, 0x07, 0xfd, 0x5b, 0xe3, 0xd8, 0xb9,
	0xc6, 0x71, 0x6f, 0x81, 0x8d, 0x41, 0x93, 0x55, 0x28, 0x1d, 0x3d, 0x68, 0x5a, 0x58, 0xe7, 0xd2,
	0xd1, 0x03, 0xa4, 0x1f, 0x26, 0x75, 0x2f, 0x1d, 0x3d, 0x74, 0x7f, 0x80, 0x8a, 0x76, 0x95, 0x2d,
	0x37, 0x2b, 0xb7, 0xdc, 0xee, 0x42, 0xcd, 0xd3, 0xb7, 0xd3, 0x40, 0x84, 0xe8, 0x61, 0xb5, 0xb8,
	0x1c, 0x52, 0x19, 0xcd, 0x50, 0xb8, 0xa2, 0x45, 0xac, 0x30, 0x39, 0x36, 0xc5, 0x6f, 0xf7, 0x4f,
	0x0b, 0x1a, 0xb9, 0x0d, 0xf0, 0xdf, 0x79, 0x4a, 0x2f, 0x4b, 0xe4, 0x57, 0x90, 0x9f, 0xd1, 0xe4,
	0x1a, 0x80, 0x19, 0x03, 0x94, 0xda, 0x28, 0xcd, 0x71, 0xc8, 0x4d, 0x58, 0x9d, 0x52, 0x18, 0x5f,
	0x15, 0xe3, 0x9b, 0xe1, 0xba, 0x8f, 0xc1, 0x99, 0x5d, 0x32, 0xa8, 0x1b, 0x9c, 0x30, 0x71, 0xaa,
	0x7a, 0x6c, 0x20, 0xf8, 0xd0, 0x8c, 0x89, 0x4d, 0x67, 0xb8, 0xae, 0x07, 0x8d, 0x74, 0xb0, 0xf8,
	0x48, 0xe8, 0x23, 0x1c, 0xf8, 0xf2, 0x1d, 0x82, 0x2b, 0x14, 0xbf, 0xc9, 0x9d, 0xec, 0x32, 0x4a,
	0xfa, 0x70, 0x7d, 0xce, 0xfa, 0xa6, 0x29, 0xc6, 0xfd, 0xad, 0x0c, 0x2b, 0x69, 0x5f, 0x2d, 0xb4,
	0x59, 0xb8, 0xd5, 0x4a, 0xb3, 0xb7, 0xda, 0x35, 0x00, 0x33, 0xfe, 0x78, 0x68, 0x73, 0x8f, 0xe5,
	0x38, 0x64, 0x23, 0x0b, 0x1a, 0x01, 0x15, 0x04, 0xe4, 0x59, 0x85, 0x37, 0x8a, 0x5d, 0x7c, 0xa3,
	0xe8, 0xc2, 0xa6, 0xf1, 0x61, 0x42, 0x67, 0xee, 0x97, 0x54, 0x46, 0xa7, 0x13, 0xfa, 0x04, 0x60,
	0x4f, 0xf0, 0x61, 0x60, 0xee, 0xc0, 0x65, 0xd4, 0xb9, 0x36, 0x4f, 0x67, 0x8a, 0xa2, 0x39, 0x0d,
	0xd2, 0x81, 0x5a, 0x5f, 0x44, 0x22, 0x14, 0xe3, 0x49, 0x72, 0xff, 0xde, 0x9c, 0xa7, 0xad, 0xb3,
	0xd5, 0x4e, 0x81, 0x66, 0x08, 0x33, 0xbd, 0xd6, 0x2e, 0x5c, 0x28, 0x88, 0x3e, 0x64, 0x67, 0xbb,
	0x5b, 0x40, 0xce, 0x87, 0xa8, 0xf1, 0x94, 0xf9, 0x43, 0x63, 0xa3, 0x46, 0x0d, 0xe1, 0x3e, 0x37,
	0xa9, 0x5b, 0x58, 0xba, 0x1b, 0x50, 0xd1, 0xf2, 0xa4, 0x17, 0x9c, 0xfc, 0x41, 0x34, 0x9f, 0xa2,
	0xd4, 0xfd, 0xb5, 0x64, 0x60, 0x73, 0x47, 0xeb, 0x41, 0xf6, 0x1a, 0x29, 0x61, 0x36, 0xae, 0xce,
	0x1a, 0x99, 0xfb, 0x14, 0xd9, 0x2b, 0x3e, 0x45, 0xca, 0xa8, 0x7a, 0xfd, 0x9c, 0xea, 0x7b, 0xdf,
	0x21, 0xff, 0xe3, 0xc5, 0xe9, 0x3a, 0xb0, 0xfa, 0x4d, 0x28, 0xde, 0xfa, 0x61, 0xfa, 0x92, 0xde,
	0xfa, 0x05, 0x1f, 0x98, 0x64, 0x15, 0xe0, 0x0d, 0x3f, 0xe6, 0xe2, 0x27, 0xde, 0x63, 0xca, 0x59,
	0x22, 0x6b, 0x59, 0x7b, 0x4b, 0xcd, 0xb0, 0x88, 0x33, 0x9d, 0x28, 0xe4, 0x94, 0xc8, 0x65, 0x20,
	0xc6, 0x56, 0x6e, 0x78, 0xa5, 0x03, 0xe4, 0x0a, 0xac, 0x1b, 0x7e, 0xbe, 0xa7, 0xa4, 0xd3, 0x20,
	0xeb, 0xb0, 0x66, 0x04, 0x69, 0x6d, 0xa5, 0xb3, 0xb2, 0xb5, 0x3b, 0x5d, 0x71, 0x1a, 0x90, 0x04,
	0x91, 0xb2, 0x9c, 0x25, 0xb2, 0x0c, 0xe5, 0xfe, 0x9e, 0xe7, 0x58, 0xfa, 0xe3, 0xcd, 0x73, 0xcf,
	0x29, 0x91, 0x1a, 0x54, 0x7a, 0x7b, 0x7d, 0xcf, 0x29, 0xef, 0x74, 0xa0, 0x9e, 0x05, 0x45, 0xbe,
	0x00, 0x1b, 0x4f, 0x45, 0x0a, 0xa3, 0x94, 0x1e, 0xb4, 0x45, 0xf2, 0x5c, 0xf3, 0x7f, 0xb0, 0x69,
	0xdd, 0xb5, 0x76, 0xf6, 0xa1, 0x6a, 0xa2, 0x22, 0xbb, 0xa9, 0x81, 0x56, 0x1e, 0x5a, 0xcc, 0xd7,
	0x22, 0x33, 0x9d, 0xcf, 0xbf, 0xdb, 0x92, 0xc1, 0x58, 0xb6, 0x8f, 0x1f, 0xc9, 0x76, 0x20, 0xb6,
	0x8f, 0x23, 0x3e, 0xc6, 0x9f, 0x19, 0x16, 0x6f, 0x47, 0xc7, 0xe3, 0xed, 0xe2, 0x6f, 0xce, 0xdb,
	0x2a, 0xfe, 0xde, 0xdc, 0xff, 0x27, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x11, 0xba, 0x84, 0xff, 0x0c,
	0x00, 0x00,
}
